config/routes.rb
Qi::Application.routes.draw do
  root 'static_pages#home'
  match '/faqs', to: 'static_pages#faqs', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def faqs
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
               <div class="container">
                   <div class="row-fluid">
                       <div class="span8">
                           <ul class="inline">
                               <li>@ QiZaryadki</li>
                               <li>
                                   <%= link_to "FAQs", faqs_path %>
                               </li>
                               <li>
                                   <%= link_to "Контакты", contact_path %>
                               </li>
                               <li>
                                   Site by
                                   <a href="#">LWD</a>
                               </li>
                           </ul>
                       </div>
                       <div class="span4 pull-right">
                           <ul class="inline">
                              <li>
                                   <a href="http://www.pinterest.com/qizaryadka/" target="_blank">
                                       <i class="fa fa-pinterest-square fa-3x"></i>
                                   </a>
                               </li>
                               <li>
                                   <a href="http://vk.com/public74392157" target="_blank">
                                       <i class="fa fa-vk fa-3x"></i>
                                   </a>
                               </li>
                               <li>
                                   <a href="https://www.youtube.com/channel/UC8zvUnAgaa3gvAvYzb2aV6Q?guided_help_flow=3" target="_blank">
                                       <i class="fa fa-youtube-square fa-3x"></i>
                                   </a>
                               </li>
                           </ul>
                       </div>
                       <!--/.span4-->
                   </div>
                   <!--/.row-fluid-->
               </div>
               <!--/.container-->
            
        </footer>

app/views/layouts/_google_analytice.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-52934163-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <a href="/" class="brand">
                    <%= image_tag "qi_logo.png", width: "230", height: "67", alt: "Qi зарядка лого", class: "pull-left visible-tablet visible-desktop" %>
                    <%= image_tag "qi_mobil_logo.png", alt: "Qi зарядка лого", class: "pull-left visible-phone" %>
                    </a>
                    <ul class=" nav pull-right">
                        <li id="nav_cart" class="cart">
                            <%= link_to contact_path do %>
                            <i class="fa fa-tablet"></i>
                            +38(066) 860-90-14
                                
                            <% end %>    
                        </li>
                        <li id="nav_cart" class="cart">
                            <%= link_to contact_path do %>
                                <i class="fa fa-tablet"></i>
                                +38(098) 335-29-11
                            <% end %>    
                            
                        </li>
                    </ul>
                </div>
            </div>   
        </div>
        <!--/.navbar-->

app/views/layouts/_script.html.erb
<%= javascript_include_tag "http://code.jquery.com/jquery-latest.js" %>
<%= javascript_include_tag "bootstrap.min" %>
<%= javascript_include_tag "jquery-picture-min" %>
<%= javascript_include_tag "jquery.magnific-popup.min" %>
<script>
$(function(){
    $('figure.responsive').picture();
    
    });
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="google-site-verification" content="SFtXucaSf2x_2n3Mj7ucjcNFIZLHboufv2E45fxIKXE" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= metamagic %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag '/favicon.ico' %>
  <meta name="p:domain_verify" content="4c2cf34b7993c8fcfa1282d2ff80fbd3"/>
  <%= render 'layouts/shim' %>
  <%= render 'layouts/google_analytice' %>
</head>
<body>
  <%= render 'layouts/header' %>
	

    <%= yield %>

    <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>

</body>
    <%= render 'layouts/script' %>
</html>

app/views/static_pages/contact.html.erb
<%
meta :title => "Контактная информация интернет магазина qi-zaryadka.com.ua. Онлайн магазин qi зарядок для мобильных телефонов qi-zaryadka.com.ua",
:description => "Контакты и данные по оплате в интернет магазине qi-zaryadka.com.ua."
%>
<div class="wrapper" style="opacity: 1;">
               <header class="shop-header">
                   
               </header>
               <section class="stockists legal">
                   <div class="container">
                       <div class="row-fluid">
                           <div class="span4">
                               <h3>Контактная информация</h3>
                               <h6>Валерий Разин</h6>
                               
                           </div>
                           <div class="span8">
                           	<a href="http://vk.com/valeriy_razin" target="_blank">
                           		<h6>Социальные сети</h6>
                            <p>ВКонтакте
                            <i class="fa fa-vk"></i>
                            </p>
                            </a> 
                            <h6>Телефон</h6>
                            <p>
                            <i class="fa fa-tablet"></i>
                            +38(066) 860-90-14
                            </p>    
                            <p>    
                            <i class="fa fa-tablet"></i>
                                +38(098) 335-29-11
                            </p>    
                            </div>
                        </div>
                    </div>
                            <div class="container">
                       <div class="row-fluid">
                             <div class="span4">
                               <h3>Способы оплаты</h3>
                                                              
                           </div>
                           <div class="span8">
                           	<h6>Webmoney (UAH)</h6>
                            <p>
                            	<i class="fa fa-money"></i>
                            U132349720523
                            
                            </p>
                            <h6>Webmoney (RUB)</h6>
                            <p>
                            	<i class="fa fa-money"></i>
                            R368293964855
                            
                            </p>
                            <h6> 
                            Карта Приватбанка</h6>	
                             <p><i class="fa fa-credit-card"></i>
                            4149 4377 2014 5778
                            </p>    
                               
                            </div>
                       </div>
                       <!--/.row-fluid-->
                   </div>
                   <!--/.container-->
               </section>
           </div>
           <!--/.wrapper-->	

app/views/static_pages/faqs.html.erb
<%
meta :title => "FAQs Часто задаваемые вопросы при оформление покупки в qi-zaryadka.com.ua. Онлайн магазин qi зарядок для мобильных телефонов qi-zaryadka.com.ua",
:description => "Вопросы про доставку, оплату и оформление заказа в интернет магазине qi-zaryadka.com.ua."
%>
<div class="wrapper" style="opacity: 1;">
               <header class="shop-header">
                   
               </header>
               <section class="stockists legal">
                   <div class="container">
                       <div class="row-fluid">
                           <div class="span4">
                               <h3>FAQs</h3>
                               <h6>Cписок наших наиболее часто задаваемых вопросов</h6>
                           </div>
                           <div class="span8">
                               <h6>Что такое беспроводная зарядка?</h6>
                               <p>Беспроводная зарядка - это инновация в мире мобильных телефонов.
Беспроводная зарядка освободит Ваш телефон от нужды использовать провод для подзарядки.</p>
                               <h6>Что нужно для того, чтобы заряжать
телефон без провода?</h6>
                               <p>Всё, что Вам нужно, это иметь телефон со встроенным ресивером и передатчик заряда.
Некоторые производители, например такие как Nokia и LG выпускают телефоны с встроенным ресивером прямо с завода. Поэтому, нет нужды покупать ресивер. Достаточно приобрести передатчик заряда.
Но другие производители, пока не сделали шаг вперёд, навстречу инновациям. И для этих производителей (Apple, Samsung) было разработано решение - встраиваемый ресивер.</p>
                               <h6>Как установить ресивер в iPhone?</h6>
                               <p>Это просто! Не нужно ломать и разбирать телефон. Для iPhone есть два вида ресивера: чехол-ресивер и ресивер без чехла.
Чехол-ресивер достаточно просто одеть на Ваш iPhone и положить на передатчик заряда.
Если на Вашем телефоне уже есть какой-либо чехол и Вы не хотите с ним расставаться, то Вам поможет ресивер, который Вы можете спрятать под чехол, соединив "хвостик" с разъёмом для подзарядки.</p>
                               <h6>Как установить ресивер в Samsung?</h6>
                               <p>С телефонами компании Samsung, всё гораздо проще. Необходимо снять крышку телефона, установить ресивер,
закрыть крышку, положить телефон на передатчик заряда.</p> 
                                  
                           </div>
                       </div>
                       <!--/.row-fluid-->
                   </div>
                   <!--/.container-->
               </section>
           </div>
           <!--/.wrapper-->